### ISSUE TITLE
Пустой транспорт

### ISSUE THREAD

**Issue by PotolokUa** [voxeltycoon/suggestions-ru#34]
Добавьте в окно уведомлений всплывающую информацию, что какой-то вид транспорта сделал несколько кругов пустым (не загруженным, упала его экономическая эффективность)

**Comment by webmgroot** [comment]
Думаю это будет в окне управления всеми тс и маршрутами. Оно же будет скоро???? Так ведь??? Его ОЧЕНЬ не хватает

**Comment by andrewpey** [comment]
Сделано в `0.80`.
