### ISSUE TITLE
Дробилка берет 2 камня вместо одного (баг)

### ISSUE THREAD

**Issue by Dumasuk2009** [voxeltycoon/suggestions-ru#63]
Камень можно переработать в гравий и каменные блоки.

В игре указано:
1 камень = 2 гравия
или
1 камень = 2 каменных блока

Так как дробилка имеет 2 входа, то мы можем подать камень по 2 линиям. Если так сделать, то дробилка будет брать на 1 выполнение любого из рецептов камень сразу с обеих линий, то есть в двойном размере.

Должно получиться ~100 гравия и ~100 каменных блоков:
![image](https://user-images.githubusercontent.com/60063543/72709703-857d9100-3b76-11ea-9581-580adf37d4ef.png)

Но мы получаем меньше:
![image](https://user-images.githubusercontent.com/60063543/72709723-8dd5cc00-3b76-11ea-9df1-6e36b9558ea4.png)

А все потому что на вход ресурсы идут по двум конвейерам и дробилка берет на 1 рецепт по одному ресурсу с каждого из конвейеров.

ПОСТ ОТРЕДАКТИРОВАН 11:20 20.01.2020. Спасибо за комментарии!

**Comment by aLegoz** [comment]
Эм... Где баг то? Я не сильно понимаю, ты когда запихиваешь в крафт станок 1 камень на выходе получаешь 2 предмета, они по очереди выходят.

**Comment by Dumasuk2009** [comment]
> Эм... Где баг то? Я не сильно понимаю, ты когда запихиваешь в крафт станок 1 камень на выходе получаешь 2 предмета, они по очереди выходят.

Выходит только 1 камень, либо 1 гравий. На скриншотах показан пустой отрезок, который заполняется 7 единицами гравия/каменного блока. И потребляется при этом 7-8 камня (с погрешностью из-за конвейеров), но не 3-4, как должно быть в случае с рецептом 1=>2

**Comment by rennug** [comment]
[image](http://puu.sh/F1wBF/3c909fc128.png)
[image](http://puu.sh/F1wD7/4cd3dc274b.png)
Все норм. А вот ты не "отрезал хвосты" у дробилок и сколько у тебя скопилось ресов на наложившихся конвейерах можно только гадать.
[image](http://puu.sh/F1zrl/b0543d60ba.png)

**Comment by Dumasuk2009** [comment]
> ![image](https://camo.githubusercontent.com/6d48ec30aca08a2d005db98ba15f45e20e80de7d/687474703a2f2f7075752e73682f46317742462f336339303966633132382e706e67)
> ![image](https://camo.githubusercontent.com/a215e62bf9cb4f1909eb2a1844599e41295facaa/687474703a2f2f7075752e73682f46317744372f346364336463323734622e706e67)
> Все норм. А вот ты не "отрезал хвосты" у дробилок и сколько у тебя скопилось ресов на наложившихся конвейерах можно только гадать.
> ![image](https://camo.githubusercontent.com/1b5f1e47361f02e7b8345efb1df9ae0b5a16331c/687474703a2f2f7075752e73682f46317a726c2f623035343364363062612e706e67)

Опытным путем мне удалось выяснить, что проблема во входах на производство, смотри:

Чистый эксперимент. Должно получиться ~100 гравия и ~100 каменных блоков:
![image](https://user-images.githubusercontent.com/60063543/72709077-2c612d80-3b75-11ea-8548-10a631616e63.png)

Но мы получаем меньше:
![image](https://user-images.githubusercontent.com/60063543/72709110-43a01b00-3b75-11ea-948c-00bd56d3c21b.png)

А все потому что на вход ресурсы идут по двум конвейерам и дробилка берет на 1 рецепт по одному ресурсу с каждого из конвейеров. Вот в чем баг оказывается :)

Спасибо, отредактировал первый пост!

**Comment by andrewpey** [comment]
Исправлено в [0.84.1](https://voxeltycoon.xyz/changelog#0.84.1).
