### ISSUE TITLE
Моддинг. Возможность вызова C# модификаций раньше инициализации менеджеров

### ISSUE THREAD

**Issue by meinroman** [voxeltycoon/suggestions-ru#74]
При создании с# модификации, в частности VoxelTycoon.Tracks.Rails.RailManager создание рельсовых блоков происходит при срабатывании OnInitialize, которое происходит, по всей видимости, до вызова всех возможных c# модов. В связи с чем нет возможности в первую загрузку игры поменять инициализируемые данные, и мод срабатывает после повторной загрузки любого сохранения. Было бы желательно в таком случае иметь возможность вызвать модификацию до инициализации менеджеров, или дать возможность инициализировать их повторно.

**Comment by andrewpey** [comment]
Готово в  [0.84](https://voxeltycoon.xyz/changelog#0.84).
