### ISSUE TITLE
Моддинг. Модификаторы доступа для классов описания стуктуры

### ISSUE THREAD

**Issue by meinroman** [voxeltycoon/suggestions-ru#75]
Необходима возможность тем или иным образом использовать через мод определенные в игре  классы с описанием структуры. В частности в менеджере VoxelTycoon.Tracks.Rails.RailManager есть приватный класс RailInfo, в котором задаются кривая и размер, который при инициализации заполняется в словарик. При создании модификации мне понадобился этот класс, но доступа к нему нет.

**Comment by andrewpey** [comment]
В данном случае эти структуры сделаны приватными не просто так — их использование извне не подразумевается, и может привести к непредсказуемым последствиям.

Однако, на свой страх и риск, их всегда можно использовать с помощью Reflection: https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/reflection.
