### ISSUE TITLE
Окно "Транспорт" кривая фильтрация по парметру ТС

### ISSUE THREAD

**Issue by aLegoz** [voxeltycoon/suggestions-ru#94]
Фильтрация работает не корректно некоторые автомобили фильтруются не в правильном порядке (На скриншотах №5)
Ожидаемое поведение: фильтруются по номеру от большего к малому и малого к большему
![](https://i.imgur.com/l3Occhk.png)
![](https://i.imgur.com/maqxx0f.png)

**Comment by inf1nitev0id** [comment]
Уже было, на самом деле это сортировка не по названию, а по времени покупки #77
А вообще-то с такой подачей это стоит в баги писать, а не в предложения
